-- MySQL Script generated by MySQL Workbench
-- Fri Dec  8 09:27:46 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema hackathondenbosch
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hackathondenbosch
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hackathondenbosch` DEFAULT CHARACTER SET utf8 ;
USE `hackathondenbosch` ;

-- -----------------------------------------------------
-- Table `hackathondenbosch`.`HOUSE_TYPES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hackathondenbosch`.`HOUSE_TYPES` (
  `house_type_ID` INT NOT NULL,
  `house_name` VARCHAR(45) NULL,
  PRIMARY KEY (`house_type_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hackathondenbosch`.`HOUSES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hackathondenbosch`.`HOUSES` (
  `house_ID` INT NOT NULL,
  `h_city` VARCHAR(45) NULL,
  `h_zipcode` VARCHAR(45) NULL,
  `h_adres` VARCHAR(45) NULL,
  `h_rent_buy` VARCHAR(45) NULL,
  `h_type` INT NULL,
  PRIMARY KEY (`house_ID`),
  INDEX `house_type_idx` (`h_type` ASC),
  CONSTRAINT `house_type`
    FOREIGN KEY (`h_type`)
    REFERENCES `hackathondenbosch`.`HOUSE_TYPES` (`house_type_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hackathondenbosch`.`USERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hackathondenbosch`.`USERS` (
  `user_ID` INT NOT NULL,
  `u_mail` VARCHAR(45) NULL,
  `u_password` VARCHAR(45) NULL,
  `u_salt` VARCHAR(45) NULL,
  `u_firstname` VARCHAR(45) NULL,
  `u_lastname` VARCHAR(45) NULL,
  PRIMARY KEY (`user_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hackathondenbosch`.`LEVELS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hackathondenbosch`.`LEVELS` (
  `level_ID` INT NOT NULL,
  `l_name` VARCHAR(45) NULL,
  PRIMARY KEY (`level_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hackathondenbosch`.`SETTINGS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hackathondenbosch`.`SETTINGS` (
  `setting_ID` INT NOT NULL,
  `p_email` VARCHAR(45) NULL,
  `p_name` VARCHAR(45) NULL,
  `p_location` VARCHAR(45) NULL,
  PRIMARY KEY (`setting_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hackathondenbosch`.`ACCOUNTS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hackathondenbosch`.`ACCOUNTS` (
  `user_ID` INT NOT NULL,
  `house_ID` INT NOT NULL,
  `level_ID` INT NOT NULL,
  `setting_ID` INT NOT NULL,
  `h_occupants` INT NULL,
  PRIMARY KEY (`user_ID`),
  INDEX `house_id_idx` (`house_ID` ASC),
  INDEX `level_id_idx` (`level_ID` ASC),
  INDEX `setting_id_idx` (`setting_ID` ASC),
  CONSTRAINT `house_id`
    FOREIGN KEY (`house_ID`)
    REFERENCES `hackathondenbosch`.`HOUSES` (`house_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_ID`)
    REFERENCES `hackathondenbosch`.`USERS` (`user_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `level_id`
    FOREIGN KEY (`level_ID`)
    REFERENCES `hackathondenbosch`.`LEVELS` (`level_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `setting_id`
    FOREIGN KEY (`setting_ID`)
    REFERENCES `hackathondenbosch`.`SETTINGS` (`setting_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
